### ISSUE TITLE
[🐛 bug report] Different renders between `cuda_spectral` and `cuda_rgb`

### ISSUE THREAD

**Issue by lastmc** [mitsuba-renderer/mitsuba3#208] opened 2022-08-26 08:41 UTC
## Summary

Hello, everyone!

We tried to render the [spaceship](https://benedikt-bitterli.me/resources/mitsuba/spaceship.zip) scene using command-line with `cuda_spectral` backend, but the rendered result seems unmatched with the RGB version.

## System configuration

- Platform: Windows 11
- Mitsuba 3 version: Mitsuba version 3.0.1 (master[e4cfa922], Windows, 64bit, 8 threads, 8-wide SIMD)
- NVidia driver version: 511.65
- Compiler: MSVC 19
- Compiled or used variants:
    * `cuda_rgb`
    * `cuda_spectral`

## Description

We added/modified some parameters in the scene file:
- `rr_depth=5`
- `samples_per_pass=64`
- `max_depth=16`
- `resx=1920`
- `resy=1080` 

The rendering results are shown as follows:

`cuda_rgb`:

![image](https://user-images.githubusercontent.com/12976583/186860160-21053e56-ff9e-4a30-ad7a-5ff80caa2399.png)

`cuda_spectral`:

![image](https://user-images.githubusercontent.com/12976583/186858803-13935117-8276-48af-9351-da8673a7d397.png)

**Comment by OldNew777** [comment] 2022-08-26 12:02
I think the problem is because Mitsuba3 unexpectedly converts conductors' `eta` and `k` from RGB to spectrum coefficients. Is there any way to mark the `rgb` nodes as raw values (just like what we can do with the `bitmap` textures)?

**Comment by merlinND** [comment] 2022-09-08 14:54
Hi @lastmc,

Thank you for reporting this! There's work (probably) related to this happening in this PR: https://github.com/mitsuba-renderer/mitsuba3/pull/235
@Speierers, would it fix the issue mentioned here? If not maybe a fix can be incorporated?

**Comment by Speierers** [comment] 2022-09-09 11:59
No unfortunately this won't be fixed in my PR. 

The non-linear calculations happening in `conductor` when using upsampled **unbounded** RGB colors (e.g. `eta` and `k`) can yield colors that are arbitrarily wrong when compared to what you will get in RGB mode. In order for this image to match (closely) in both modes, you will need to provide spectrum curves for `eta` and `k` instead. In RGB modes those will be pre-integrated to compute RGB colors which is much more well-behaved and should give you similar results compared to doing the computations in spectral mode.

For instance you could try with `silver` or `aluminum` from [this list](https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_bsdfs.html#conductor-ior-list)

**Closed by Speierers** 2022-09-09 11:59 UTC
