### ISSUE TITLE
Circular artifacts on spheres for far away sensors

### ISSUE THREAD

**Issue by maxfrei750** [mitsuba-renderer/mitsuba3#512] opened 2023-01-30 17:01 UTC
## Summary

When the sensor is far away (e.g. 100 or 1000) from a sphere, this results in circular artifacts:
![test](https://user-images.githubusercontent.com/36265931/215543473-b27f5a04-0501-46d3-8ca3-696430a8ca4c.png)

## System configuration

System information:
```
  CPU: 12th Gen Intel(R) Core(TM) i9-12900K
  GPU: NVIDIA GeForce RTX 3090
  Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
  NVidia driver: 525.85.05
  LLVM: 11.1.0

  Dr.Jit: 0.4.0
  Mitsuba: 3.2.0
     Is custom build? True
     Compiled with: Clang 11.1.0
     Variants:
        scalar_rgb
        cuda_ad_rgb
        llvm_ad_rgb
        cuda_ad_mono
        llvm_ad_mono
        llvm_ad_spectral
        cuda_ad_spectral
```
## Description

See above.

## Steps to reproduce

```
import mitsuba as mi

mi.set_variant("cuda_ad_rgb")

SCENE_DICT = {
    "type": "scene",
    "sphere": {
        "type": "sphere",
        "bsdf": {
            "type": "principled",
        },
    },
    "fill_light": {
        "type": "constant",
        "radiance": 1.0,
    },
    "integrator": {
        "type": "prb"
    },
    "sensor": {
        "type":
            "orthographic",
        "to_world":
            mi.ScalarTransform4f.look_at(
                origin=[0, 0, 1000],    # [0, 0, 10] works fine
                target=[0, 0, 0],
                up=[0, 1, 0]),
        "film": {
            "type": "hdrfilm",
            "pixel_format": "luminance" if "mono" in mi.variant() else "rgb",
        }
    },
}


def render_sphere():
    scene = mi.load_dict(SCENE_DICT)
    image = mi.render(scene, spp=1024)
    mi.util.write_bitmap("test.png", image)


if __name__ == "__main__":
    render_sphere()

```

Maybe it is related to Clang 11.1.0 or LLVM 11.1.0 (since your CI uses version 10)?

**Comment by hesom** [comment] 2023-01-31 14:55
For me this only happens on cuda_* variants, and only if the near plane is far away from the sphere. For example it looks fine, if I set `"near_clip":  990` on the orthographic camera. Since moving the near plane also moves the ray origin this could be a numerical issue in the [GPU ray/sphere intersection code](https://github.com/mitsuba-renderer/mitsuba3/blob/0e497163e13a27d7afe5beb591f6fd7bac7ce80d/src/shapes/optix/sphere.cuh#L15). From a quick glance it looks almost identical to the [CPU version](https://github.com/mitsuba-renderer/mitsuba3/blob/0e497163e13a27d7afe5beb591f6fd7bac7ce80d/src/shapes/sphere.cpp#L346), except that the CPU version uses double precision, if I interpret the first few lines correctly, which could be an explanation.

**Comment by njroussel** [comment] 2023-02-06 09:53
Hi @maxfrei750 

@hesom is correct I believe, this is a numerical issue. I have already started writing a ray-sphere intersection routine which should be more numerically stable. I think we should be done with it this week. I'll keep this thread updated.

**Comment by maxfrei750** [comment] 2023-02-06 09:57
@njroussel @hesom Thanks for the replies! Glad to hear that this is already being worked on.

**Comment by njroussel** [comment] 2023-02-07 16:30
The fix has been pushed to `master`: (https://github.com/mitsuba-renderer/mitsuba3/commit/7d46e10154b19945b2e4ee97ba7876ac917692c8 and https://github.com/mitsuba-renderer/mitsuba3/commit/0b483bff5fdcc6d9663d73626bb1dd46674311a6).

I've tried in on your reproducer @maxfrei750, it got rid of the "ringing" entirely.

**Closed by njroussel** 2023-02-07 16:30 UTC

**Comment by maxfrei750** [comment] 2023-02-07 17:32
@njroussel Thanks!
