### ISSUE TITLE
Can't scatter to same target more than once inside symbolic loop (3.6.0)

### ISSUE THREAD

**Issue by tomas16** [mitsuba-renderer/mitsuba3#1427] opened 2024-12-04 18:19 UTC
### Discussed in https://github.com/mitsuba-renderer/mitsuba3/discussions/1425

<div type='discussions-op-text'>

<sup>Originally posted by **tomas16** December  3, 2024</sup>
# `dr.scatter` issues

Hi, I'm porting an existing algorithm to work with 3.6.0 and running into some issues. Not sure if these may be bugs or if I'm doing things wrong. Most of the issues are related to using `dr.scatter` to write results to output arrays inside a symbolic loop. I can't share the full algorithm, but it's mostly straightforward raytracing. At every bounce, I want to record various bits of information such as intersection location, costi/costt, and some others.

The general structure of the algorithm is

```python
@dr.syntax
def algo(scene: mi.Scene, ray: mi.Ray3f, max_bounces: int):
    num_rays = dr.width(ray)
    numel = num_rays * max_bounces      # for each ray, we want to record information per bounce

    # output arrays (write-only)
    out_xyz = dr.zeros(mi.Float, numel * 3)
    out_costi = dr.zeros(mi.Float, numel)

    # these 2 output arrays get written to multiple times per iteration, with different value/index/active
    out_active = dr.zeros(mi.Bool, numel)           # one per bounce, per ray
    out_raystatus = dr.zeros(mi.UInt, num_rays)     # one per ray

    ray_idx = dr.arange(mi.UInt, num_rays)

    active = mi.Bool(True)                          # expands to num_rays inside the loop body (not shown)
    bounce = dr.zeros(mi.UInt, num_rays)
    while dr.hint(active & (bounce < max_bounces), mode='symbolic'):
    # or simply and equivalently:
    # while active & (bounce < max_bounces):

        # index vector into the output arrays for the current bounce/iteration
        idx = ray_idx + bounce * num_rays

        # Do raytracing stuff (si = scene.ray_intersect() etc)
        # ... a bunch of variables are created here

        # this works
        dr.scatter(out_costi, si.wi.z, idx, active)

        # this doesn't work, but used to before 3.6.0
        dr.scatter(out_xyz, si.p, idx, active)

        # this works (in real algo there's other stuff in between)
        dr.scatter(out_active, False, idx, mask)            # mask is computed and handles special cases only
        dr.scatter(out_active, active, idx, active)         # main update

        # this doesn't work (in real algo there's 4 lines like this with other stuff in between)
        # -> can only scatter once to out_raystatus inside the loop body
        dr.scatter(out_raystatus, 1, ray_idx, mask2)
        dr.scatter(out_raystatus, 2, ray_idx, mask3)
```

## `out_costi`
The simplest case, `out_costi`, performs a single scatter of a scalar value per ray and works fine.

## `out_xyz`
The 2nd case, `out_xyz`, is very similar, only this time I want to record a `Point3f` per ray. The implementation shown above worked pre-3.6.0. Now I get

```
    dr.scatter(out_xyz, si.p, idx, active)
RuntimeError: Variable r476 remains dirty despite an attempt to evaluate it.
This normally indicates the following situation:
1. You executed an operation causing a *side effect*, e.g., a
...
```

I don't understand why `out_xyz` would have to get evaluated. Like `out_costi`, it's never read from, and is only ever used as the target of `dr.scatter`.

If I initialize `out_xyz` as `out_xyz = dr.zeros(mi.Point3f, numel)`, I don't get an error. Running this with toy data and converting to a numpy array at the end, I'm expecting a 7x5x3 ndarray, representing a max of 7 bounces and 5 rays. `out_xyz.ravel()` seems to give me:
* x coordinate of bounce 0, all 5 rays
* x coordinate of bounce 1, all 5 rays
* ...
* after the x coordinates of all bounces and all rays, the remainder of the array is all zeros. The Y and Z coordinates aren't present.

I also tried initializing it to other array types like `Array3f`, which resulted in the error `TypeError: drjit.scatter(): 'target' argument must be a dynamic 1D array!`

**Given this used to work pre-3.6.0 and it doesn't result in an error when using `Point3f`, I wonder if this may be a bug?**

## `out_active`

Doing multiple scatter operations with different value/active args to `out_active` works.

## `out_raystatus`

Multiple scatter operations to `out_raystatus` result in the same error as encountered by `out_xyz`: `RuntimeError: Variable r372 remains dirty despite an attempt to evaluate it.`.

The only difference with the previous case is that `out_active` is a larger array of all bounces and all rays, whereas `out_raystatus` is one value per ray. And of course `mi.Bool` vs `mi.UInt`.

# Versions
* mitsuba 3.6.0
* drjit 1.0.1
* python 3.12.7
* llvm 16
</div>

**Comment by tomas16** [comment] 2024-12-04 18:20
Closing this issue here, should go in drjit

**Comment by merlinND** [comment] 2024-12-07 08:37
Closing as duplicate of https://github.com/mitsuba-renderer/mitsuba3/issues/1427, since the discussion is already happening there.

**Closed by merlinND** 2024-12-07 08:37 UTC
