### ISSUE TITLE
'path' integrator with cuda backend breaks Mitsuba in v. 3.2.0 - DrJit critial compiler error: unknown variable

### ISSUE THREAD

**Issue by mr-Mojo** [mitsuba-renderer/mitsuba3#482] opened 2023-01-07 18:17 UTC
Hi! It seems the new update introduced a strange bug: when rendering the bunny scene from the pose estimation example, Mitsuba 3.2.0 breaks with the `path` integrator and the `cuda_ad_rgb` backend. It works with other integrators (I tried `prb_reparam`, `direct`, `direct_reparam`), and it also works when using `path` with the `llvm_ad_rgb` backend. 

My sys info: 
```
System information:

  OS: Ubuntu 20.04.4 LTS
  CPU: 12th Gen Intel(R) Core(TM) i9-12900K
  GPU: NVIDIA GeForce RTX 3090
  Python: 3.9.7 (default, Sep 16 2021, 13:09:58) [GCC 7.5.0]
  NVidia driver: 520.61.05
  CUDA: 11.7.64
  LLVM: 12.0.0

  Dr.Jit: 0.4.0
  Mitsuba: 3.2.0
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

```

MWE to reproduce: 

```python
import drjit as dr
import mitsuba as mi
mi.set_variant('cuda_ad_rgb')
from mitsuba.scalar_rgb import Transform4f as T


scene = mi.load_dict({
    'type': 'scene',
    'integrator': {'type': 'path'},
    'sensor':  {
        'type': 'perspective',
        'to_world': T.look_at(
                        origin=(0, 0, 2),
                        target=(0, 0, 0),
                        up=(0, 1, 0)
                    ),
        'fov': 60,
        'film': {
            'type': 'hdrfilm',
            'width': 64,
            'height': 64,
            'rfilter': { 'type': 'gaussian' },
            'sample_border': True
        },
    },
    'wall': {
        'type': 'obj',
        'filename': '../../mitsuba_scenes/scenes/meshes/rectangle.obj',
        'to_world': T.translate([0, 0, -2]).scale(2.0),
        'face_normals': True,
        'bsdf': {
            'type': 'diffuse',
            'reflectance': { 'type': 'rgb', 'value': (0.5, 0.5, 0.5) },
        }
    },
    'bunny': {
        'type': 'ply',
        'filename': '../../mitsuba_scenes/scenes/meshes/bunny.ply',
        'to_world': T.scale(6.5),
        'bsdf': {
            'type': 'diffuse',
            'reflectance': { 'type': 'rgb', 'value': (0.3, 0.3, 0.75) },
        },
    },
    'light': {
        'type': 'obj',
        'filename': '../../mitsuba_scenes/scenes/meshes/sphere.obj',
        'emitter': {
            'type': 'area',
            'radiance': {'type': 'rgb', 'value': [1e3, 1e3, 1e3]}
        },
        'to_world': T.translate([2.5, 2.5, 7.0]).scale(0.25)
    }
})

params = mi.traverse(scene)

# when commenting this next line out, it runs, but breaks with a similar error at iteration 481
initial_vertex_positions = dr.unravel(mi.Point3f, params['bunny.vertex_positions'])

for j in range(1000):
    new_image = mi.render(scene=scene, params=params, seed=j, spp=16)
    print(f"Iteration {j}")
```

This MWE - as is - crashes even before the 1st iteration, with the error message `Critical Dr.Jit compiler failure: jit_var(r690): unknown variable!`. If I comment out the line `initial_vertex_positions` it runs, but breaks at iteration 481 (always) with a similar error: `Critical Dr.Jit compiler failure: jit_var(r1597543): unknown variable!`

With both Mitsuba 3.0.2 and 3.1.0, any combination of integrator and backend works.

**Comment by njroussel** [comment] 2023-01-09 07:24
Hi @mr-Mojo 

I've tired running the "Object pose estimation" tutorial and your MWE, both run without any issues on my end :confused: 

Could you double check your Drjit/Mitsuba version inside of your code by printing `mi.__version__` and `dr.__version__`? It's possible that Python is pickup up a local build too, depending on where you're launching it from.

**Comment by mr-Mojo** [comment] 2023-01-09 08:15
Hey @njroussel , thanks for the quick reply. The output is as expected: 

```python
print(mi.__version__)
3.2.0
print(dr.__version__)
0.4.0
```

**Comment by mr-Mojo** [comment] 2023-01-09 08:25
Also, it seems I have to redact my previous claims about `prb_reparam` working (I wasn't patient enough to actually let it run through all 1000 iterations, sorry). 

`prb_reparam` breaks at Iter 966 with `Critical Dr.Jit compiler failure: jit_var(r4418871): unknown variable!`. 
`volpath` breaks at Iter 898 with `Critical Dr.Jit compiler failure: jit_var(r16373146): unknown variable!`.

**Comment by njroussel** [comment] 2023-01-09 08:35
Thanks. That actually makes some sense: the upgrade to 3.2.0 was mostly a backend update, there weren't any changes directly to the integrators.

I'll try running these optimizations for longer, hopefully I can reproduce them.

**Comment by mr-Mojo** [comment] 2023-01-11 08:55
Hey @njroussel were you able to reproduce the crashes?

**Comment by njroussel** [comment] 2023-01-12 07:36
I've tried quite a few things and never encountered this error.
I was also using these versions of Mitsuba/DrJit for at least a few weeks before they were made available on PyPI, without seeing something similar. 

This might be something specific to your setup. My best suggestion now would be to build the projects yourself, locally on your machine. Specifically, in `debug` mode and try to re-run these experiments with a debugger.
(I'd recommend uninstalling any PyPI versions you have before building locally.)

**Comment by v-san** [comment] 2023-01-27 11:28
Hello. Since 3.2.0 release I had also experienced seemingly random crashes with the same type of error message:
`Critical Dr.Jit compiler failure: jit_var(********): unknown variable!`
I mainly use cuda_ad_mono backend, direct_reparam integrator. Crashes may come and go depending on anything - material model, texture used by a material, running debug, etc. 
For example, there could be no crashes with principled material model. Then I change to lambert model and have a crash. But if I then change texture used by lambert material, the crash may disappear.
I also experienced no problems with the same code on earlier versions.

```
System information:

  OS: Ubuntu 22.04.1 LTS
  CPU: AMD Ryzen 9 5950X 16-Core Processor
  GPU: NVIDIA GeForce RTX 2070 SUPER
  Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
  NVidia driver: 525.60.11
  LLVM: 16.0.0

  Dr.Jit: 0.4.0
  Mitsuba: 3.2.0
     Is custom build? False
     Compiled with: GNU 11.3.0
     Variants:
        scalar_rgb
        cuda_ad_mono
        cuda_ad_rgb
        cuda_ad_spectral
```

**Comment by njroussel** [comment] 2023-01-27 16:09
I was finally able to reproduce this issue and identify the bug.

For some reason, with a local build I was unable to reproduce the problem originally but with the PyPI package I can reproduce what @mr-Mojo  describes. I'll leave this to some difference in the compilers used. 

This [specific commit](https://github.com/mitsuba-renderer/drjit-core/commit/30e623ecb236c87b39f9ac0331a9167b0ecd472f#diff-7a57b7a20f4b405d02cc19c10a2e39491e07b4a2ff3aac926dcc0a0c392fe318) should get rid of the issue.

The good news it that it's currently fixed in Dr.Jit, but we haven't pushed a new release out yet. You can pull all the changes in Dr.Jit up to (at least) [this commit](https://github.com/mitsuba-renderer/drjit/commit/794ecba8cd1c970886170fd29221da157514d07d) and build the package locally.

Thank you both for reporting this.

**Closed by njroussel** 2023-01-27 16:09 UTC
