### ISSUE TITLE
4 billion variables

### ISSUE THREAD

**Issue by saeedhd96** [mitsuba-renderer/mitsuba3#404] opened 2022-11-24 01:27 UTC
## Summary

Critical Dr.jit compiler failure after iterating many many times

## Description

I get this error on Mitsuba after 1500 iterations on an inverse rendering task for a cbox and a lego bulldozer inside it, and the resoultion 256 * 256, spp8, prb method. What could be the reason? It is definitely not that my tasks are too many rays "at once" because this only appears after many many iterations.

`Critical Dr.Jit compiler failure: DrJit has created more than 2^32 (4 billion) variables, which is currently the limit. Bug Wenzel to fix this (it will involve sorting scheduled variables by scope ID instead of variable ID and making the counter big enough that it will never overflow..).`

**Comment by DoeringChristian** [comment] 2022-11-24 22:38
As far as I understand it the problem is that drjit uses 32 bit integers as variable indices. When allocating variables a global index is incremented. This would result in an overflow after 2^32 variables have been created. As the message states fixing this would "involve making the counter big enough that it will never overflow".

**Comment by wjakob** [comment] 2022-11-24 22:39
It will be fixed soon, stay tuned.

**Comment by njroussel** [comment] 2022-11-30 12:59
Hi @saeedhd96 

This has been fixed, you should no longer have this issue with the latest release (v3.1.1).

**Closed by njroussel** 2022-11-30 12:59 UTC

**Comment by wjakob** [comment] 2022-11-30 13:17
Not quite, right? It will be fixed when #410 is merged.

**Comment by njroussel** [comment] 2022-11-30 13:24
As the issue only appears after a large number of iterations, I think this was related to the sampler state "leak" fixed here: https://github.com/mitsuba-renderer/drjit/commit/5e9da65f0e834927349713a5da1ae6e4e207ee16
