### ISSUE TITLE
Roughconductor polarized wi=wo bug

### ISSUE THREAD

**Issue by opueyociutad** [mitsuba-renderer/mitsuba3#957] opened 2023-10-26 07:59 UTC
## Summary

Roughconductor material in polarized mode returns NaN if wi=wo.

## System configuration

OS: Ubuntu 22.04.3 LTS
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  GPU: NVIDIA GeForce GTX 1070
  Python: 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0]
  NVidia driver: 525.125.06
  CUDA: 11.5.119
  LLVM: 15.0.7

  Dr.Jit: 0.4.3
  Mitsuba: 3.4.0
     Is custom build? True
     Compiled with: GNU 11.4.0
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb
        cuda_ad_mono_polarized

## Description

Roughconductor returns NaN if wi=wo, this happens due to `H = normalize(wi+wo)`, which implies wi=wo=H. When building  the reference axis frames for polarization `s_axis_in` and `s_axis_out`, `cross(H, wi) = (0,0,0)`, and its normalization is NaN.
In this retroreflection case, $R_{\perp} = R_{\parallel}$, hence any axis would work.

## Steps to reproduce

I bring here a minimal reproducer for this bug:

```python3
import mitsuba as mi
mi.set_variant('cuda_ad_mono_polarized')

import drjit as dr
from drjit.cuda.ad import Array3f

BSDF = mi.load_dict({
    'type': 'roughconductor'
})

BSDF_CONTEXT = mi.BSDFContext(mi.TransportMode.Importance)
x = Array3f(0,0,0)
n = dr.normalize(Array3f(0, 0, 1))
wiwo_global = dr.normalize(Array3f(0, 0, 1))

si = dr.zeros(mi.SurfaceInteraction3f)
si.p = x
si.n = n
si.sh_frame = mi.Frame3f(si.n)
si.wi = si.to_local(wiwo_global)
wo = si.to_local(wiwo_global)
bsdf_val_local = BSDF.eval(BSDF_CONTEXT, si, wo)
bsdf_val_global = si.to_world_mueller(bsdf_val_local, -si.wi, wo)

print(bsdf_val_local)
print(bsdf_val_global)
```

**Comment by njroussel** [comment] 2024-01-09 07:27
Hi @opueyociutad 

Thank you for the detailed bug report.

As far as I can tell, this is a duplicate of #757. I'll have a look at it over there - I haven't really dug into it yet. My initial thoughts are that we can indeed arbitrarily pick an axis.

**Closed by njroussel** 2024-01-09 07:27 UTC
