### ISSUE TITLE
[🐛 bug report] Update the 'film.crop_offset' parameter leads to slow rendering and memory leak

### ISSUE THREAD

**Issue by swordigo1995** [mitsuba-renderer/mitsuba3#399] opened 2022-11-21 15:26 UTC
## Summary

Hi, I use Mitsuba3 to render a synthetic dataset with many small image patches. I use the 'sensor.film.crop_offset' parameter to render only a crop in the full image. However, I find the process of updating this parameter may cause issues like a slowdown of the rendering and memory leak. 

## System configuration

System information:

  OS: Ubuntu 20.04
  CPU: Intel Core i7-7700
  GPU: NVIDIA RTX 2080Ti
  Python version: 3.9.13
  CUDA version: 11.6
  NVidia driver: 515.57

  Dr.Jit version: 0.2.2
  Mitsuba version: 3.0.2 (installed from pip)

## Description
I use 'cuda_ad_rgb' variant in the sample code. However, I also find a similar issue in the 'llvm_ad_rgb' variant.

I found the rendering will be much slower (about 90 times slower in the following sample), and the GPU memory will be increased if I update this parameter (about 500MB memory increase in a 2000 iteration loop). The utilization of GPU is also extremely low in this case (0% shown in the nvidia-smi).
If I do not update this parameter, everything will be ok.

I'm not sure if there is a bug behind it, if not, any idea to increase the speed and avoid the memory issue in this case?
Thank you and looking forward to your reply!

## Steps to reproduce
The sample code (modified from [this tutorial](https://mitsuba.readthedocs.io/en/stable/src/rendering/editing_a_scene.html#)):
```
import time
import random
from tqdm import tqdm

import drjit as dr
import mitsuba as mi
mi.set_variant('cuda_ad_rgb')

scene = mi.load_file("../scenes/simple.xml")
params = mi.traverse(scene)
resolution = params['sensor.film.size']

iter_num = 2000
patch_size = 32
for i in tqdm(range(iter_num)):
    patch_range = [resolution[0] - patch_size, resolution[1] - patch_size]
    patch_position = [int(random.random() * patch_range[0]), int(random.random() * patch_range[1])]
    params['sensor.film.crop_offset'] = mi.ScalarPoint2u(patch_position)
    params['sensor.film.crop_size'] = mi.ScalarVector2u(patch_size)

    # Give a red tint to light1 and a green tint to light2
    params['light1.intensity.value'] *= [1.5, 0.2, 0.2]
    params['light2.intensity.value'] *= [0.2, 1.5, 0.2]

    # Translate the teapot a little bit
    V = dr.unravel(mi.Point3f, params['teapot.vertex_positions'])
    V.z += 0.0005
    params['teapot.vertex_positions'] = dr.ravel(V)

    start_time = time.time()
    params.update();
    modified_image = mi.render(scene, spp=256)
    print('Time duration: {}s'.format(time.time() - start_time))
```

**Comment by swordigo1995** [comment] 2022-11-24 02:38
BTW, I find the 'scalar_rgb' mode does not suffer from this problem.

**Comment by njroussel** [comment] 2022-11-30 13:26
I'm not able to reproduce the memory leak, nor the slowdown in rendering time.
We've pushed a few significant bug fixes and general performance improvements over the past few weeks. I'd recommend you upgrade to v3.1.1. If you're still seeing this issue after the upgrade, please tell us.

As to why you have such a low GPU utilization, this behaviour is expected. In your script you are essentially rendering tiny 32x32 images which simply do not fully occupy the GPU.  Also, you can't have more than one iteration working at the same time on the GPU as you are changing `vertex_positions` which requires a GPU synchronization otherwise you might be changing the vertices as the previous iteration is still using them.

**Comment by swordigo1995** [comment] 2022-12-01 06:37
Thanks for your response! @njroussel 

I updated the mitsuba to v3.1.1 and re-run the sample code, but I still find the memory leak problem.
I tested with 'llvm_ad_rgb' variant this time, and I recorded the CPU & memory utilization in the monitor as shown in the video below.

As to the speed of rendering and device utilization, if I comment out the line of "params['sensor.film.crop_offset'] = mi.ScalarPoint2u(patch_position)", the utilization will be near 100% even with rendering the tiny 32x32 images (as shown in the beginning of the video). However, i expected that the behaviors with or without random `crop_offset` are not such distinguishable because the crop size and spp are the same. I'm wondering the reason behind this significant speed / utilization up, maybe caused by a technique like caching? 

https://user-images.githubusercontent.com/12183862/204969495-b2030108-f2b6-4dfb-9235-540ecafd0b94.mp4

**Comment by njroussel** [comment] 2022-12-01 08:38
Oh my bad, I misunderstood. I thought you were comparing against a version of the script where you comment out both lines:
```python
    params['sensor.film.crop_offset'] = mi.ScalarPoint2u(patch_position)
    params['sensor.film.crop_size'] = mi.ScalarVector2u(patch_size)
```

I am able to reproduce the same results as you now. Here's what's going on:

This is a simplified explanation, but this should at least give you an idea of what's happening. Mitsuba uses a just-in-time compiler - Dr.Jit - which records all operations and then compiles them into a CPU or GPU kernel once you need to evaluate (in your example it's when you call `mi.render()`. Dr.Jit caches these kernels in case you need to call them again. It's unfortunate in your example, but every time you change `crop_offset` it will generate a new kernel, hence a cache miss and a new compilation.
I believe the memory increase when using the `crop_offset` is simply the kernel cache growing over time. For the utilization, I believe there are drops in performance because we need to compile a new kernel at each iteration and the compilation doesn't fully utilize all cores :disappointed: .

**Comment by swordigo1995** [comment] 2022-12-01 10:22
Okay, thanks for your explanation! I got it🙂.

There are still some points I want your support and advice:
1. It seems like updating the scene parameters (e.g., materials, translation in the script) do not need to compile a new kernel. Is there any hint why the change of `crop_offset` need to re-compile? Does it happen when I update any sensor/film related parameters? It is possible to prevent a new compilation when I render a new patch?
2. Since I want to generate a dataset of image patches in a variable scene, any suggestion for the workaround of this problem? For example, can I run multiple mitsuba3 processes in my GPU to increase the utilization (though scene assets may be copied multiple times..)? Is there any API to clear the JIT kernel cache which I can prevent the out of memory issue?

**Comment by njroussel** [comment] 2022-12-01 12:04
1) There are two "types" or rather flavours of variables: scalar types and vectorized types. Scalar types represent just a single value, and these get baked into your kernels and hence need a re-compilation. For a `Film`, `crop_offset` is implemented as a `ScalarPoint2u` and not a `Point2u`. There's somewhat of a tradeoff, with scalar types they get baked into the kernel and that allows for a lot of constant propagation. 
If you wanted to prevent a new compilation you would need to modify this in the C++ source code, and then also use `dr::make_opaque` which will further guarantee that the value will not be baked into the kernel.  

2) Take a look at `dr.flush_kernel_cash`, as the name suggests this function will flush the kernel cache so you shouldn't run out of memory anymore.
Multiple process should work I believe. There's a bit more work still to be done to submit jobs to different CUDA  streams, which would allow you to effectively do this a single process.

**Comment by swordigo1995** [comment] 2022-12-01 15:49
Thanks for your reply! It's really helpful. 🫡

**Comment by njroussel** [comment] 2022-12-01 15:53
Great, let me close this issue for now :)

**Closed by njroussel** 2022-12-01 15:53 UTC
