### ISSUE TITLE
Laplacian of the displacement

### ISSUE THREAD

**Issue by Yishun99** [mitsuba-renderer/mitsuba3#943] opened 2023-10-16 07:16 UTC
Hi , I am working on baking displacement map via a differentiable learning framework. 
And I wonder if the LargeStep method can be used for achieving better results. 
However, things come with different since I only want to learn scalar displacement instead of the 3-dim position per vertex. 
Generally speaking, is it possible to apply the LargeStep method on more geometry parameters, such as displacement, normal, and/or mix of them?

**Comment by bathal1** [comment] 2023-10-17 08:13
Hi, I will close this as it is a duplicate of [this issue](https://github.com/rgl-epfl/large-steps-pytorch/issues/18). We can continue the conversation there.

**Closed by bathal1** 2023-10-17 08:13 UTC
