### ISSUE TITLE
caustics optimization tutorial not working with mitsuba v3

### ISSUE THREAD

**Issue by tstigen** [mitsuba-renderer/mitsuba3#967] opened 2023-11-04 23:11 UTC
## Summary

Running the caustics optimization tutorial from the mitsuba page, the simulation fails with the following error. 

Critical Dr.Jit compiler failure: jit_optix_check(): API error 7251 (OPTIX_ERROR_PIPELINE_LINK_ERROR): "Pipeline link error" in D:\a\drjit\drjit\ext\drjit-core\src\optix_core.cpp:392.

This is with a clean install environment in conda using python 3.11.5. 

## System configuration

System information:

  OS: Windows 10 x64
  CPU: Intel 7700k
  GPU: nVidia 1080
  Python version: 3.11.5
  LLVM version: 14.06
  CUDA version: 12.3
  NVidia driver: 546.01

  Dr.Jit version: 0.4.3
  Mitsuba version: 3.4
     Compiled with: pip install
     Variants compiled: cuda_ad_rgb

## Description
With the cuda variant I can run the code down to where the simulation starts to run (running scalar_rgb fails much earlier in the "displacement texture" cell with numpy() not an attribute error). Is this tutorial meant to run with mitsuba 3 and drjit 0.4.3 on python 3.11? If not, do you have a conda environment that works? Could you share the .yml for the environment? 

## Steps to reproduce

1. Follow the caustics optimzation page tutorial notebook. The failure occurs on the cell that starts with"import time" with the "Critical Dr.Jit compiler failure: jit_optix_check(): API error 7251 (OPTIX_ERROR_PIPELINE_LINK_ERROR): "Pipeline link error" in D:\a\drjit\drjit\ext\drjit-core\src\optix_core.cpp:392." error. 
2.

**Comment by njroussel** [comment] 2023-11-09 16:05
Hi @tstigen 

Thanks for the bug report. I think this is a duplicate of #826. Let me close this, and re-open that one.

**Closed by njroussel** 2023-11-09 16:05 UTC

**Comment by tstigen** [comment] 2024-01-13 04:19
Can confirm that rolling back to GeForce 531.79 enabled it work again. That is the last r525 driver I believe. It seems all the r535 drivers through 546.XX do not work with my 1080.
