### ISSUE TITLE
"an illegal memory access was encountered" when doing the optimization

### ISSUE THREAD

**Issue by zhaoguangyuan123** [mitsuba-renderer/mitsuba3#689] opened 2023-04-25 07:58 UTC
Error occurs randomly when continuously do the optimization with mitsuba. 
Is it related to the issue https://github.com/mitsuba-renderer/mitsuba3/issues/662?

In my case, the bug occurs when I use LLVM or CUDA_AD_RGB. 

```
Caustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic OptimizationCaustic Optimization

Critical Dr.Jit compiler failure: cuda_check(): API error 0700 (CUDA_ERROR_ILLEGAL_ADDRESS): "an illegal memory access was encountered" in /project/ext/drjit-core/src/init.cpp:448.
```

System information:
OS: Ubuntu 18.04
CPU: Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
GPU: NVIDIA RTX A6000
Python version: 3.8.13
CUDA version: 12.0
NVidia driver: 525.105.17

**Comment by njroussel** [comment] 2023-06-08 07:51
Let me close this issue and refer you to #703. We haven't figure out the cause yet, but from all signs we suspect a bug in Dr.Jit.

**Closed by njroussel** 2023-06-08 07:51 UTC
