### ISSUE TITLE
[🐛 bug report]RuntimeError: jitc_var_eval(r300230): placeholder variables are used to record computation symbolically and cannot be scheduled for evaluation!

### ISSUE THREAD

**Issue by Chenguoz** [mitsuba-renderer/mitsuba3#124] opened 2022-07-21 16:12 UTC
## Summary

The following error occurs when I use gpu rendering（`cuda_ad_rgb`），But it can be executed successfully when using the variant`scalar_rgb`
```
Traceback (most recent call last):
  File "rander.py", line 18, in <module>
    read_file(category, idx)
  File "rander.py", line 11, in read_file
    image = mi.render(scene, spp=256)
  File "/home/anaconda3/python3.8/site-packages/mitsuba/python/util.py", line 496, in render
    return dr.custom(_RenderOp, scene, sensor, params, integrator,
  File "/home/anaconda3/python3.8/site-packages/drjit/router.py", line 5566, in custom
    output = inst.eval(**{ k: _dr.detach(v) for k, v in kwargs.items() })
  File "/home/anaconda3/python3.8/site-packages/mitsuba/python/util.py", line 358, in eval
    return self.integrator.render(
RuntimeError: jitc_var_eval(r300230): placeholder variables are used to record computation symbolically
and cannot be scheduled for evaluation! This error message could appear for
the following reasons:

1. You are using DrJit's loop or virtual function call recording feature
   and tried to perform an operation that is not permitted in this restricted
   execution mode. Please see the documentation of recorded loops/virtual
   function calls to learn about these restrictions.

2. You are accessing a variable that was modified as part of a recorded
   loop and forgot to specify it as a loop variable. Please see the
   drjit::Loop documentation for details.
```

## System configuration
- Platform: Linux CentOS 7
- Python version: 3.8.13
- Mitsuba 3 version: 3.0.0

## Code
```
import os
import mitsuba as mi
from tqdm import tqdm
mi.set_variant("cuda_ad_rgb")

def read_file(category, idx):
    filename = 'temp/{}_scene_{}.xml'.format(category, idx)
    scene = mi.load_file(filename)
    image = mi.render(scene, spp=256)
    mi.util.write_bitmap("out/{}_{}.jpg".format(category, idx), image)

if __name__ == '__main__':
    category = 'airplane'
    for idx in tqdm(range(10)):
        read_file(category, idx)
```

**Comment by merlinND** [comment] 2022-07-21 20:59
Hello @Chenguoz,

This is surprising, since your Python code looks fine to me. Could you please post one of the XML files you are rendering to see if we can reproduce it locally?

**Comment by Chenguoz** [comment] 2022-07-22 05:47
Thank you for your reply @merlinND !
This is a XML file example，and tested on RTX3080TI with driver version is 510.73.05.

    <scene version="0.6.0">
        <integrator type="path">
            <integer name="maxDepth" value="-1"/>
        </integrator>
        <sensor type="perspective">
            <float name="farClip" value="100"/>
            <float name="nearClip" value="0.1"/>
            <transform name="toWorld">
                <lookat origin="3,3,3" target="0,0,0" up="0,0,1"/>
            </transform>
            <float name="fov" value="25"/>
            
            <sampler type="ldsampler">
                <integer name="sampleCount" value="64"/>
            </sampler>
            <film type="hdrfilm">
                <integer name="width" value="1080"/>
                <integer name="height" value="1080"/>
                <rfilter type="gaussian"/>
                <boolean name="banner" value="false"/>
            </film>
        </sensor>
        
        <bsdf type="roughplastic" id="surfaceMaterial">
            <string name="distribution" value="ggx"/>
            <float name="alpha" value="0.05"/>
            <float name="intIOR" value="1.46"/>
            <rgb name="diffuseReflectance" value="1,1,1"/> 
        </bsdf>
        
    
        <shape type="sphere">
            <float name="radius" value="0.025"/>
            <transform name="toWorld">
                <translate x="-0.32291463017463684" y="-0.23374223709106445" z="0.35145071148872375"/>
            </transform>
            <bsdf type="diffuse">
                <rgb name="reflectance" value="0.1972380598222698,0.29655846002730996,0.9344250786145335"/>
            </bsdf>
        </shape>
    
        <shape type="sphere">
            <float name="radius" value="0.025"/>
            <transform name="toWorld">
                <translate x="-0.2729928493499756" y="-0.20818796753883362" z="0.46219754219055176"/>
            </transform>
            <bsdf type="diffuse">
                <rgb name="reflectance" value="0.22274752339548176,0.28633638782567467,0.9318771452440091"/>
            </bsdf>
        </shape>
    

        <shape type="rectangle">
            <ref name="bsdf" id="surfaceMaterial"/>
            <transform name="toWorld">
                <scale x="10" y="10" z="1"/>
                <translate x="0" y="0" z="-0.5"/>
            </transform>
        </shape>
        
        <shape type="rectangle">
            <transform name="toWorld">
                <scale x="10" y="10" z="1"/>
                <lookat origin="-4,4,20" target="0,0,0" up="0,0,1"/>
            </transform>
            <emitter type="area">
                <rgb name="radiance" value="6,6,6"/>
            </emitter>
        </shape>
    </scene>

**Comment by Chenguoz** [comment] 2022-07-22 07:34
@merlinND Hey!
 I finally solved the bug by changing the XML file from version 0.6.0 to version 3.0.0 and changing the names of the components inside.
Thank you!  :）

**Comment by dvicini** [comment] 2022-07-25 09:07
I took a look at the problem: the issue is that the `ldsampler` was not supporting GPU/LLVM modes. I pushed a fix on master (https://github.com/mitsuba-renderer/mitsuba3/commit/98a8ecb2390ebf35ef5f54f28cccaf9ab267ea48). It will take until the next bugfix release for this fix to propagate to the pre-built Python packages. If you use these, you can also consider using one of the stratified samplers: https://mitsuba.readthedocs.io/en/latest/src/generated/plugins_samplers.html

**Closed by dvicini** 2022-07-25 09:07 UTC
