### ISSUE TITLE
remesh mitsuba3 output geometry produce strange bias

### ISSUE THREAD

**Issue by xdobetter** [mitsuba-renderer/mitsuba3#722] opened 2023-05-09 07:36 UTC
## Summary

I optimize geometry use mitsuba3 and work well,after optimize end I use remesh tool handle output3 geometry,but I find it produce strange bias.I think the reason for this problem may come from two aspects:

- mitsuba3 output geometry
- remesh tool([Instant Meshes](https://github.com/wjakob/instant-meshes))

So I did two experiments.
Experiment A I use a GT geometry and remesh it,remesh is good.
Experiment B I use mitsuba3 read the GT geometry  and do nothing then output the geometry,I find produce strange bias.
Experiment C,I guess there may be a problem with the algorithm of mitsuba3 output ply, so I use igl to output ply,I find produce strange bias too.
Below are the result of experiment A,B,C.

![sum](https://user-images.githubusercontent.com/26523963/237017543-4ce37ccf-ad08-4bd2-b841-ceef6ff21b71.png)

## System configuration

System information:

  OS: Ubuntu 20.04.5 LTS
  CPU: Intel Xeon Processor (Skylake, IBRS)
  GPU: Tesla V100S-PCIE-32GB
Tesla V100S-PCIE-32GB
  Python: 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55) [GCC 11.3.0]
  NVidia driver: 520.61.05
  CUDA: 11.8.89
  LLVM: 12.0.0

  Dr.Jit: 0.4.1
  Mitsuba: 3.2.1
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Steps to reproduce

If you want to reproduce result,there is the code and data  for experiments A,B,C.

[result.zip](https://github.com/mitsuba-renderer/mitsuba3/files/11428377/result.zip)

The remesh code for A, B, and C is the same, see below

```python

import subprocess
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('input',  type=str)
parser.add_argument('output', type=str)
# parser.add_argument('vertex', type=str)

args = parser.parse_args()

input_obj_fn = args.input  
output_obj_fn = args.output 

subprocess.run(['instant_meshes', '-o', output_obj_fn, '-t', '32', '-S', '10', '-d', '-p', '6','-v',"60000", input_obj_fn])
```

Remesh the output of experiments B and C using the input of experiment A as the input

The code of B,C:

```python
import mitsuba as mi
import torch
import igl
import numpy as np
mi.set_variant("cuda_ad_rgb")

def wrap_tensor(v) -> torch.Tensor:
    '''
        mi.float/mi.Int -> mi.TensorXf ->torch.Tensor
    '''
    vTensor=mi.TensorXf(v,shape=(len(v)//3,3)).torch()
    return vTensor

inputPath=""
outputPath=""
mesh = mi.load_dict({
    "type": "obj",
    "filename": "", # mesh path
    "face_normals": False,
})

params = mi.traverse(mesh)

vertex_positions = wrap_tensor(params['vertex_positions']).cpu().numpy()
faces = wrap_tensor(params['faces']).cpu().numpy().astype(np.int32)

mesh.write_ply(outputPath) # Experiment B
igl.write_triangle_mesh(outputPath,vertex_positions,faces) # Experiment C
```

**Comment by njroussel** [comment] 2023-05-09 12:06
Hi @xdobetter 

I ran experiment B and cannot reproduce it.

I might have misunderstood the issue, here is the exact code I'm running:
```python
import mitsuba as mi
mi.set_variant("cuda_ad_rgb")

inputPath="result/EB/mesh_B_origin.ply"
outputPath="result/EB/out.ply"
mesh = mi.load_dict({
    "type": "ply",
    "filename": inputPath,
    "face_normals": False,
})

params = mi.traverse(mesh)

mesh.write_ply(outputPath) # Experiment B
```

It's litterally just reading and writing some geometry.

**Comment by njroussel** [comment] 2023-05-09 12:08
To be clear, I inspected `out.ply` and everything seems fine.

**Comment by xdobetter** [comment] 2023-05-10 12:26
Sorry,maybe I didn't make it clear enough.The problem is that if you remesh the geometry written by mitsuba3, it will have a weird bias in its geometry.So I try A,B,C experiment to check the bias;
The remesh method is ([Instant Meshes](https://github.com/wjakob/instant-meshes))
Experiment A is a direct remesh of the geometry which I gave;
Experiment B is remesh the geometry which written by mitsuba3,and the input geometry of mitsuba3 is the input geometry of experiment A;
Experiment C is the same as Experiment B, the only difference between them is that the output mesh method is changed to igl.

**Comment by bathal1** [comment] 2023-05-12 08:55
Am I understanding this correctly ?
- Exp. A: You load a mesh in Instant Meshes, remesh it, and write it back as PLY. Mitsuba is not involved at all.
- Exp. B: You write a mesh as PLY from Mitsuba, remesh it, and write it back as PLY. Mitsuba is used both for loading the mesh and for

**Comment by bathal1** [comment] 2023-05-12 08:58
Am I understanding this correctly ?

- Exp. A: You load a mesh in Instant Meshes, remesh it, and write it back as PLY. Mitsuba is not involved at all.
- Exp. B: You first load the input mesh from exp. A with Mitsuba, write is back as PLY using Mitsuba's `write_ply`. You *then* remesh it, and write it back as PLY.
- Exp. C: Same setup as exp. B, except the mesh is written using libigl's writer before remeshing.

**Comment by bathal1** [comment] 2023-05-12 09:22
This issue seems to be a consequence of using the PLY file format. PLY files store all data (normals, UVs, etc.) *per vertex*, and faces merely index into the vertex data list. Since all attributes are stored together, you cannot store a single vertex with different UV coordinates for the different faces it belongs to. To do so, the vertex data needs to be duplicated, and therefore the connectivity of the mesh is altered. 

Your input mesh has UV seams. When writing it as a PLY file, the vertices along those seams will be duplicated, and therefore the connectivity information along them will be lost. This is problematic for remeshing, as it relies on this information. You can notice that what you called "weird bias" is actually a displacement of the surface along those very seams. This is expected, since remeshing will treat each part of your mesh as an individual piece, as they are not connected anymore.

This is not an issue with OBJ files, since they store buffers of different sizes for each attributes, and faces can index independently into each of them. Therefore, the connectivity information is maintained. 

This does not seem to be an issue with mitsuba, but more about the file format you used. For example, if you loaded the mesh with libigl, and wrote it back as PLY using libigl as well, you would likely get the same result.

That said, Mitsuba uses a similar data layout as the PLY file format for storing meshes. Therefore, even writing the mesh from Mitsuba as OBJ would likely cause the same issue. If you do not care about the UV coordinates, what you could do is remove the duplicate vertices before processing the mesh (see [here ](https://github.com/rgl-epfl/large-steps-pytorch/blob/8310713d6a4ab8a88c279f228fd39579a2ca2bcd/scripts/geometry.py#L3)for an example).

I will close this as it is not a bug. If you wish to discuss your use case further, please feel free to open a discussion [here](https://github.com/mitsuba-renderer/mitsuba3/discussions)

**Closed by bathal1** 2023-05-12 09:22 UTC

**Comment by xdobetter** [comment] 2023-05-13 09:05
Thank you very much for your detailed advice and guidance, I will try as soon as possible.
