### ISSUE TITLE
How to render scene with more than 10k spp?

### ISSUE THREAD

**Issue by brabbitdousha** [mitsuba-renderer/mitsuba3#1335] opened 2024-10-09 10:17 UTC
## Summary

Hi, I am using python with mitsuba3, and I need to render a reference image with more than 10k spp, maybe 100k spp. However,  with ```mi.set_variant("cuda_ad_rgb")``` and simply calling ```mi.render(scene=scene, spp=spp)``` won't let me do it due to the limitations of MC samples,
 I tried to rewrite the render() and put a loop in it like [simple.py](https://github.com/DoeringChristian/mitsuba3-experiments/blob/0a3aab7c6ea61f80f1b68a31e6c9a9626b2a8312/simple.py), but I can only render 14777 spp at most, I think there might be some hardware limitations.
However, I think this task is a fundamental requirement, so is there anyway I can render for more than 10k spp?

## System configuration

System information:

  OS: windows
  CPU: intel i9-13900H
  GPU: RTX 4060 laptop
  Python version: 3.9
  CUDA version: 12.0
  NVidia driver: 550.54.14

  Dr.Jit version: 0.4.4
  Mitsuba version: 3.5.0

**Comment by brabbitdousha** [comment] 2024-10-09 10:35
I tried again with ```dr.set_flag(dr.JitFlag.VCallRecord, False)
& dr.set_flag(dr.JitFlag.LoopRecord, False)```  
this could be running for more than 10k spp, but much slower

**Comment by andyyankai** [comment] 2024-10-11 03:30
You might want to consider to render an image in multiple loops using different seed.
`
for i in range(npass):
    if i == 0:
        image = mi.render(scene, integrator=integrator, spp=spp, seed=i) / npass
    else:
        image += mi.render(scene, integrator=integrator, spp=spp, seed=i) / npass


`

**Comment by brabbitdousha** [comment] 2024-10-11 04:27
> You might want to consider to render an image in multiple loops using different seed.
> 
> ```
> for i in range(npass):
>     if i == 0:
>         image = mi.render(scene, integrator=integrator, spp=spp, seed=i) / npass
>     else:
>         image += mi.render(scene, integrator=integrator, spp=spp, seed=i) / npass
> ```

Hi, thanks for the advice, I tried this but the memory is still increasing, so still, not working. Anyway, thanks!

**Comment by njroussel** [comment] 2024-11-19 09:42
I'll close this for now, it seems to be a duplicate of #1353.

The code that @andyyankai  shared should work. Rendering in multiple passes does not increase memory usage.

**Closed by njroussel** 2024-11-19 09:42 UTC
