### ISSUE TITLE
[❔ other question] "device or resource busy" for DrJit CUDA / LLVM in Jupyter notebook

### ISSUE THREAD

**Issue by Pikachuxxxx** [mitsuba-renderer/mitsuba3#203] opened 2022-08-24 14:53 UTC
## Summary

DrJit samples causing Float type exception with both cuda and LLVM backends in Jupyter Notebook

## System configuration

*For bug report, please enter information regarding your system configuration<- [remove this]*

- Platform: Windows 10/11
- Compiler: LLVM/MSVC
- Python version: 3.8
- Mitsuba 3 version: 3.0.1
- Compiled variants:
    * `scalar_rgb`

## Description

I've tried running the basic drjit sample and LLVM doesn't work due the backend being inactive as per issues #153 I've tried this on multiple machines by manual installation and setting the ENV variable manually and via python, even when using drjit.cuda with the following code I run into this in the jupyter notebook. However when using only CUDA it works  fine when I run it on command line in .py file

![image](https://user-images.githubusercontent.com/45527623/186450434-31b7a54a-2eef-4895-bdd0-9e4fd2e5509c.png)

**Comment by njroussel** [comment] 2022-08-24 17:51
Hi @Pikachuxxxx !

I see that your environment variable is a path to a folder, rather than the DLL file itself. Can you change it to specifically hold the absolute path to  `LLVM-C.dll`?

As for the CUDA error, can you enable

**Comment by njroussel** [comment] 2022-08-24 17:55
I'm actually a bit confused. Have you only compiled the `scalar_rgb` variant? 
The build process will not build the CUDA/LLVM backends for `drjit` if you only have the `scalar_rgb` variant.

**Comment by Pikachuxxxx** [comment] 2022-08-24 18:17
> Hi @Pikachuxxxx !
> 
> 
> 
> I see that your environment variable is a path to a folder, rather than the DLL file itself. Can you change it to specifically hold the absolute path to  `LLVM-C.dll`?

I've tried and it doesn't work at all LLVM backend won't work on any of my windows machines

**Comment by Speierers** [comment] 2022-08-25 06:40
What is the version of the NVidia driver installed on your machine?

**Comment by njroussel** [comment] 2022-08-25 06:44
Ok, that's weird.

Can you tell me more about the environment that's being used?
- How did you install drjit?
- Are you using Anaconda (or something similar)?
- Have you tried using a standalone LLVM installation rather than the one that ships with MSVC? Like [this one](https://community.chocolatey.org/packages/llvm) for example.

---

For the CUDA error, are you able to run some other Python code that uses CUDA (like PyTorch) in Jupyter?
Can you give me your Nvidia driver version and GPU model?

The error feels more like a weird configuration with your Jupyter setup than a DrJit bug. Somehow the GPU isn't accessible from Jupyter.

**Comment by Pikachuxxxx** [comment] 2022-08-25 15:40
> * How did you install drjit?

I've used pip3 for drjit

> * Have you tried using a standalone LLVM installation rather than the one that ships with MSVC? Like [this one](https://community.chocolatey.org/packages/llvm) for example.

I've installed the one from LLVM github releases

> For the CUDA error, are you able to run some other Python code that uses CUDA (like PyTorch) in Jupyter? Can you give me your Nvidia driver version and GPU model?

Driver Version: 516.94       
CUDA Version: 11.7
NVIDIA GeForce RTX 2060

Looks like an issue with Jupyter none of my GPUs seems to showing up with tensorflow

**Comment by merlinND** [comment] 2022-09-06 08:32
Hi @Pikachuxxxx,

Were you able to narrow down this issue?

> Looks like an issue with Jupyter none of my GPUs seems to showing up with tensorflow

It sounds like the problem is unrelated to DrJit so I will close this issue, but feel free to reopen it.

**Closed by merlinND** 2022-09-06 08:32 UTC

**Comment by kookiny** [comment] 2022-09-27 14:36
Hello @Pikachuxxxx, I'm having exactly the same issue on windows.
My GPU was not showing up with tensorflow in the beginning so I fixed it.
But still this error comes up
`RuntimeError: device or resource busy: device or resource busy`
Did you fix it? is it working well now?
