### ISSUE TITLE
Variants problem with measured polarized material

### ISSUE THREAD

**Issue by duongnlt** [mitsuba-renderer/mitsuba3#959] opened 2023-10-27 16:21 UTC
## System configuration

System information:

 OS: Ubuntu 20.04
 CPU: 12th Gen Intel(R) Core(TM) i5-12400
 GPU: NVIDIA GeForce RTX 3060
 Python version: 3.8.10 (default, May 26 2023, 14:05:08) [GCC 9.4.0]
 LLVM version: 10.0.0
 CUDA version: 12.2
 NVidia driver: 535.104.12

Dr.Jit version: 0.4.3
Mitsuba version: 3.4.0
Compiled with: Clang 10.0.0     
Variants compiled: 
scalar_rgb
scalar_spectral
llvm_rgb
llvm_ad_rgb
llvm_spectral
cuda_rgb
cuda_ad_rgb
cuda_spectral
scalar_rgb_polarized
scalar_rgb_polarized_double
scalar_spectral_polarized
scalar_spectral_polarized_double
cuda_rgb_polarized
cuda_rgb_polarized_double
cuda_spectral_polarized
cuda_spectral_polarized_double
llvm_spectral_polarized

## Description

When I render any `measured_polarized` object, whose BSDF loaded from BSDF [file](https://drive.google.com/file/d/1BpTjlY6fydEh5Sij9nOQ8_37WVStnDJp/view?usp=sharing), with `cuda_spectral_polarized` or `llvm_spectral_polarized` , this error appears:
```
jit_var_registry_attr(): entry with domain="mitsuba::BSDF", name="flags" not found!
Segmentation fault (core dumped)
```

## Steps to reproduce
I build Mitsuba 3 from source with `Dockerfile`
```
FROM nvidia/cuda:12.2.0-base-ubuntu20.04 AS mitsuba3

RUN apt update
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
RUN apt install -y git \
  clang-10 libc++-10-dev libc++abi-10-dev cmake ninja-build \
  libpng-dev libjpeg-dev \
  libpython3-dev python3-distutils \
  python3-pytest python3-pytest-xdist python3-numpy \
  python-is-python3 pip \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*



ENV CC=clang-10
ENV CXX=clang++-10

RUN git clone --recursive https://github.com/mitsuba-renderer/mitsuba3 /mitsuba3

WORKDIR /mitsuba3
RUN mkdir build
ADD mitsuba.conf build/mitsuba.conf
RUN cd build && cmake -GNinja .. && ninja

ENV PYTHONPATH="/mitsuba3/build/python:$PYTHONPATH"
ENV PATH="/mitsuba3/build:$PATH"

# build with some basic python packages
RUN pip install \
    jupyterlab \
    matplotlib \
    opencv-python

# start jupyter lab
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]
EXPOSE 8888
```

then the Python script is here:

```python
import mitsuba as mi
import drjit as dr
import numpy as np

mi.set_variant('cuda_spectral_polarized')
from mitsuba import ScalarTransform4f as T


sensor = mi.load_dict({
    'type': 'perspective',
    'to_world': T.translate([0,0,-10]),
    'sampler': {
        'type': 'multijitter',
        'sample_count': 256
    },
    'film': {
        'type': 'hdrfilm',
        'width': 512,
        'height': 512,
        'pixel_format': 'rgb',
        'rfilter': {
            'type': 'gaussian'
        }
    }
        
})

integrator = mi.load_dict({
                'type': 'path',
            })
sphere = mi.load_dict({
            'type': 'sphere',
                
            'to_world': T.scale(20),
            'bsdf': {
                'type': 'measured_polarized',
                'filename': '../scene/BRDF/16_pink_silicon_inpainted.pbsdf',
                'alpha_sample': 0.1
            },
})

scene = mi.load_dict({
            'type':'scene',
            'integrator': integrator,
            'sensor': sensor,
            'object': sphere,
            
            'light': {'type': 'constant'},   
    
})
image = mi.render(scene)
```

**Comment by njroussel** [comment] 2023-10-31 08:20
Hi @duongnlt 

This is a duplicate of https://github.com/mitsuba-renderer/mitsuba3/issues/694.

**Closed by njroussel** 2023-10-31 08:20 UTC
