### ISSUE TITLE
Invalid IR emitted for nested emitter defined in Python

### ISSUE THREAD

**Issue by dvicini** [mitsuba-renderer/mitsuba3#533] opened 2023-02-09 10:53 UTC
Hi,

I was trying to create an emitter in Python that would wrap the standard environment emitter. There seems to be an issue when routing virtual function calls through such a nested emitter construction.

My code looks like this:
```
import mitsuba as mi
import drjit as dr
import numpy as np
mi.set_variant('llvm_ad_rgb')

class NestedEmitter(mi.Emitter):

  def __init__(self, props):
    mi.Emitter.__init__(self, props)
    self.nested_emitter = props['nested_emitter']

  def eval(self, si, active):
    return self.nested_emitter.eval(si, active)

mi.register_emitter('nestedemitter', lambda props: NestedEmitter(props))

scene = mi.load_dict(
    {
        'type': 'nestedemitter',
        'nested_emitter': {
            'type': 'envmap',
            'bitmap': mi.Bitmap(np.ones((32, 32, 3))),
        },
    },
)

emitter = mi.EmitterPtr(scene)

si = dr.zeros(mi.SurfaceInteraction3f)

# This works
# s = scene.eval(si, True)
# print(r)

# This fails
r = emitter.eval(si, True)
print(r)
```

Directly calling the function on the loaded emitter is fine, but when I call through an EmitterPtr, I get the following invalid LLVM IR that misses a declaration for `mask`:
```
Critical Dr.Jit compiler failure: jit_llvm_compile(): parsing failed. Please see the LLVM IR and error message below:

define void @drjit_351fa1486832d7f940c1e0b1883c0b64(i64 %start, i64 %end, i8** noalias %params) #0 {
entry:
    br label %body

body:
    %index = phi i64 [ %index_next, %suffix ], [ %start, %entry ]
    %f1_1 = insertelement <8 x float> undef, float 0x3fe0000000000000, i32 0
    %f1 = shufflevector <8 x float> %f1_1, <8 x float> undef, <8 x i32> zeroinitializer
    %rd2_p1 = getelementptr inbounds i8*, i8** %params, i32 3
    %rd2 = load i8*, i8** %rd2_p1, align 8, !alias.scope !2
    %r3_1 = insertelement <8 x i32> undef, i32 1578, i32 0
    %r3 = shufflevector <8 x i32> %r3_1, <8 x i32> undef, <8 x i32> zeroinitializer
    %p4 = bitcast <8 x i1> %mask to <8 x i1>
    %f5_0 = bitcast i8* %rd2 to float*
    %f5_1 = getelementptr float, float* %f5_0, <8 x i32> %r3
    %f5 = call <8 x float> @llvm.masked.gather.v8f32(<8 x float*> %f5_1, i32 4, <8 x i1> %p4, <8 x float> zeroinitializer)
    %r6_1 = insertelement <8 x i32> undef, i32 1581, i32 0
    %r6 = shufflevector <8 x i32> %r6_1, <8 x i32> undef, <8 x i32> zeroinitializer
    %f7_0 = bitcast i8* %rd2 to float*
    %f7_1 = getelementptr float, float* %f7_0, <8 x i32> %r6
    %f7 = call <8 x float> @llvm.masked.gather.v8f32(<8 x float*> %f7_1, i32 4, <8 x i1> %p4, <8 x float> zeroinitializer)
    %f8 = fmul <8 x float> %f1, %f7
    %f9 = call <8 x float> @llvm.fma.v8f32(<8 x float> %f1, <8 x float> %f5, <8 x float> %f8)
    %r10_1 = insertelement <8 x i32> undef, i32 1677, i32 0
    %r10 = shufflevector <8 x i32> %r10_1, <8 x i32> undef, <8 x i32> zeroinitializer
    %f11_0 = bitcast i8* %rd2 to float*
    %f11_1 = getelementptr float, float* %f11_0, <8 x i32> %r10
    %f11 = call <8 x float> @llvm.masked.gather.v8f32(<8 x float*> %f11_1, i32 4, <8 x i1> %p4, <8 x float> zeroinitializer)
    %r12_1 = insertelement <8 x i32> undef, i32 1680, i32 0
    %r12 = shufflevector <8 x i32> %r12_1, <8 x i32> undef, <8 x i32> zeroinitializer
    %f13_0 = bitcast i8* %rd2 to float*
    %f13_1 = getelementptr float, float* %f13_0, <8 x i32> %r12
    %f13 = call <8 x float> @llvm.masked.gather.v8f32(<8 x float*> %f13_1, i32 4, <8 x i1> %p4, <8 x float> zeroinitializer)
    %f14 = fmul <8 x float> %f1, %f13
    %f15 = call <8 x float> @llvm.fma.v8f32(<8 x float> %f1, <8 x float> %f11, <8 x float> %f14)
    %f16 = fmul <8 x float> %f1, %f15
    %f17 = call <8 x float> @llvm.fma.v8f32(<8 x float> %f1, <8 x float> %f9, <8 x float> %f16)
    %r18_0 = trunc i64 %index to i32
    %r18_1 = insertelement <8 x i32> undef, i32 %r18_0, i32 0
    %r18_2 = shufflevector <8 x i32> %r18_1, <8 x i32> undef, <8 x i32> zeroinitializer
    %r18 = add <8 x i32> %r18_2, <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
    %p19_0 = trunc i64 %end to i32
    %p19_1 = insertelement <8 x i32> undef, i32 %p19_0, i32 0
    %p19_2 = shufflevector <8 x i32> %p19_1, <8 x i32> undef, <8 x i32> zeroinitializer
    %p19 = icmp ult <8 x i32> %r18, %p19_2
    %f20_p1 = getelementptr inbounds i8*, i8** %params, i32 4
    %f20_p2 = load i8*, i8** %f20_p1, align 8, !alias.scope !2
    %f20_p3 = bitcast i8* %f20_p2 to float*
    %f20_p4 = getelementptr inbounds float, float* %f20_p3, i64 %index
    %f20_p5 = bitcast float* %f20_p4 to <8 x float>*
    %f20 = select <8 x i1> %p19, <8 x float> %f17, <8 x float> zeroinitializer
    store <8 x float> %f20, <8 x float>* %f20_p5, align 32, !noalias !2, !nontemporal !3
    %r21_1 = insertelement <8 x i32> undef, i32 1579, i32 0
    %r21 = shufflevector <8 x i32> %r21_1, <8 x i32> undef, <8 x i32> zeroinitializer
    %f22_0 = bitcast i8* %rd2 to float*
    %f22_1 = getelementptr float, float* %f22_0, <8 x i32> %r21
    %f22 = call <8 x float> @llvm.masked.gather.v8f32(<8 x float*> %f22_1, i32 4, <8 x i1> %p4, <8 x float> zeroinitializer)
    %r23_1 = insertelement <8 x i32> undef, i32 1582, i32 0
    %r23 = shufflevector <8 x i32> %r23_1, <8 x i32> undef, <8 x i32> zeroinitializer
    %f24_0 = bitcast i8* %rd2 to float*
    %f24_1 = getelementptr float, float* %f24_0, <8 x i32> %r23
    %f24 = call <8 x float> @llvm.masked.gather.v8f32(<8 x float*> %f24_1, i32 4, <8 x i1> %p4, <8 x float> zeroinitializer)
    %f25 = fmul <8 x float> %f1, %f24
    %f26 = call <8 x float> @llvm.fma.v8f32(<8 x float> %f1, <8 x float> %f22, <8 x float> %f25)
    %r27_1 = insertelement <8 x i32> undef, i32 1678, i32 0
    %r27 = shufflevector <8 x i32> %r27_1, <8 x i32> undef, <8 x i32> zeroinitializer
    %f28_0 = bitcast i8* %rd2 to float*
    %f28_1 = getelementptr float, float* %f28_0, <8 x i32> %r27
    %f28 = call <8 x float> @llvm.masked.gather.v8f32(<8 x float*> %f28_1, i32 4, <8 x i1> %p4, <8 x float> zeroinitializer)
    %r29_1 = insertelement <8 x i32> undef, i32 1681, i32 0
    %r29 = shufflevector <8 x i32> %r29_1, <8 x i32> undef, <8 x i32> zeroinitializer
    %f30_0 = bitcast i8* %rd2 to float*
    %f30_1 = getelementptr float, float* %f30_0, <8 x i32> %r29
    %f30 = call <8 x float> @llvm.masked.gather.v8f32(<8 x float*> %f30_1, i32 4, <8 x i1> %p4, <8 x float> zeroinitializer)
    %f31 = fmul <8 x float> %f1, %f30
    %f32 = call <8 x float> @llvm.fma.v8f32(<8 x float> %f1, <8 x float> %f28, <8 x float> %f31)
    %f33 = fmul <8 x float> %f1, %f32
    %f34 = call <8 x float> @llvm.fma.v8f32(<8 x float> %f1, <8 x float> %f26, <8 x float> %f33)
    %f35_p1 = getelementptr inbounds i8*, i8** %params, i32 5
    %f35_p2 = load i8*, i8** %f35_p1, align 8, !alias.scope !2
    %f35_p3 = bitcast i8* %f35_p2 to float*
    %f35_p4 = getelementptr inbounds float, float* %f35_p3, i64 %index
    %f35_p5 = bitcast float* %f35_p4 to <8 x float>*
    %f35 = select <8 x i1> %p19, <8 x float> %f34, <8 x float> zeroinitializer
    store <8 x float> %f35, <8 x float>* %f35_p5, align 32, !noalias !2, !nontemporal !3
    %r36_1 = insertelement <8 x i32> undef, i32 1580, i32 0
    %r36 = shufflevector <8 x i32> %r36_1, <8 x i32> undef, <8 x i32> zeroinitializer
    %f37_0 = bitcast i8* %rd2 to float*
    %f37_1 = getelementptr float, float* %f37_0, <8 x i32> %r36
    %f37 = call <8 x float> @llvm.masked.gather.v8f32(<8 x float*> %f37_1, i32 4, <8 x i1> %p4, <8 x float> zeroinitializer)
    %r38_1 = insertelement <8 x i32> undef, i32 1583, i32 0
    %r38 = shufflevector <8 x i32> %r38_1, <8 x i32> undef, <8 x i32> zeroinitializer
    %f39_0 = bitcast i8* %rd2 to float*
    %f39_1 = getelementptr float, float* %f39_0, <8 x i32> %r38
    %f39 = call <8 x float> @llvm.masked.gather.v8f32(<8 x float*> %f39_1, i32 4, <8 x i1> %p4, <8 x float> zeroinitializer)
    %f40 = fmul <8 x float> %f1, %f39
    %f41 = call <8 x float> @llvm.fma.v8f32(<8 x float> %f1, <8 x float> %f37, <8 x float> %f40)
    %r42_1 = insertelement <8 x i32> undef, i32 1679, i32 0
    %r42 = shufflevector <8 x i32> %r42_1, <8 x i32> undef, <8 x i32> zeroinitializer
    %f43_0 = bitcast i8* %rd2 to float*
    %f43_1 = getelementptr float, float* %f43_0, <8 x i32> %r42
    %f43 = call <8 x float> @llvm.masked.gather.v8f32(<8 x float*> %f43_1, i32 4, <8 x i1> %p4, <8 x float> zeroinitializer)
    %r44_1 = insertelement <8 x i32> undef, i32 1682, i32 0
    %r44 = shufflevector <8 x i32> %r44_1, <8 x i32> undef, <8 x i32> zeroinitializer
    %f45_0 = bitcast i8* %rd2 to float*
    %f45_1 = getelementptr float, float* %f45_0, <8 x i32> %r44
    %f45 = call <8 x float> @llvm.masked.gather.v8f32(<8 x float*> %f45_1, i32 4, <8 x i1> %p4, <8 x float> zeroinitializer)
    %f46 = fmul <8 x float> %f1, %f45
    %f47 = call <8 x float> @llvm.fma.v8f32(<8 x float> %f1, <8 x float> %f43, <8 x float> %f46)
    %f48 = fmul <8 x float> %f1, %f47
    %f49 = call <8 x float> @llvm.fma.v8f32(<8 x float> %f1, <8 x float> %f41, <8 x float> %f48)
    %f50_p1 = getelementptr inbounds i8*, i8** %params, i32 6
    %f50_p2 = load i8*, i8** %f50_p1, align 8, !alias.scope !2
    %f50_p3 = bitcast i8* %f50_p2 to float*
    %f50_p4 = getelementptr inbounds float, float* %f50_p3, i64 %index
    %f50_p5 = bitcast float* %f50_p4 to <8 x float>*
    %f50 = select <8 x i1> %p19, <8 x float> %f49, <8 x float> zeroinitializer
    store <8 x float> %f50, <8 x float>* %f50_p5, align 32, !noalias !2, !nontemporal !3
    br label %suffix

suffix:
    %index_next = add i64 %index, 8
    %cond = icmp uge i64 %index_next, %end
    br i1 %cond, label %done, label %body, !llvm.loop !4

done:
    ret void
}

declare <8 x float> @llvm.fma.v8f32(<8 x float>, <8 x float>, <8 x float>)


declare <8 x float> @llvm.masked.gather.v8f32(<8 x float*>, i32, <8 x i1>, <8 x float>)

!0 = !{!0}
!1 = !{!1, !0}
!2 = !{!1}
!3 = !{i32 1}
!4 = !{!"llvm.loop.unroll.disable", !"llvm.loop.vectorize.enable", i1 0}

attributes #0 = { norecurse nounwind "frame-pointer"="none" "no-builtins" "no-stack-arg-probe" "target-cpu"="znver2" "target-features"="-vzeroupper,-avx512pf,-tsxldtrk,+cx16,+sahf,-tbm,-avx512ifma,+sha,+crc32,-fma4,-vpclmulqdq,+prfchw,+bmi2,-cldemote,+fsgsbase,-ptwrite,-amx-tile,-uintr,-gfni,+popcnt,-widekl,+aes,-avx512bitalg,-movdiri,+xsaves,-avx512er,-avxvnni,-avx512fp16,-avx512vnni,-amx-bf16,-avx512vpopcntdq,-pconfig,+clwb,-avx512f,+xsavec,+clzero,-pku,+mmx,-lwp,+rdpid,-xop,+rdseed,-waitpkg,-kl,-movdir64b,+sse4a,-avx512bw,+clflushopt,+xsave,-avx512vbmi2,+64bit,-avx512vl,-serialize,-hreset,-invpcid,-avx512cd,+avx,-vaes,-avx512bf16,+cx8,+fma,-rtm,+bmi,-enqcmd,+rdrnd,+mwaitx,+sse4.1,+sse4.2,+avx2,+fxsr,+wbnoinvd,+sse,+lzcnt,+pclmul,-prefetchwt1,+f16c,+ssse3,-sgx,-shstk,+cmov,-avx512vbmi,-amx-int8,+movbe,-avx512vp2intersect,+xsaveopt,-avx512dq,+sse2,+adx,+sse3" }

drjit_351fa1486832d7f940c1e0b1883c0b64:13:28: error: use of undefined value '%mask'
    %p4 = bitcast <8 x i1> %mask to <8 x i1>
                           ^
```

It also doesn't seem to happen for other nested emitters, e.g. if I nest a point light it works just fine.

The error occurs both when using the pip-installed Mitsuba and the latest master. I am bit surprised at this error, since we both have extensively used environment maps and Python-defined plugins in the past.

Any ideas what's happening here @wjakob @njroussel?

Best,
Delio

**Comment by njroussel** [comment] 2023-02-09 11:35
Hi @dvicini !

Thanks for the reproducer, I can recreate it. I've bisected a few different versions, it looks like this has always been broken. I'll try to track this down.

(FWIW this issue does not concern `cuda_*` variants)

**Comment by dvicini** [comment] 2023-02-09 12:04
Great, appreciate you taking a look. I don't have time to look into it myself, but having this fixed would be quite useful for me :)

**Comment by njroussel** [comment] 2023-02-09 12:11
You can use `dr.set_flag(dr.JitFlag.VCallOptimize, False)` as a workaround if this is really urgent :smile_cat:.

**Comment by njroussel** [comment] 2023-02-20 08:50
Hi 

This was fixed in Drjit (https://github.com/mitsuba-renderer/drjit-core/pull/57). I've updated the submodules on mitsuba `master`.

**Closed by njroussel** 2023-02-20 08:50 UTC
