### ISSUE TITLE
grey and white furnace test with roughplastic BSDF

### ISSUE THREAD

**Issue by GMBethsoft** [mitsuba-renderer/mitsuba3#1155] opened 2024-04-29 20:31 UTC
Hi,
I tried white and grey furnace test with the roughplastic BSDF and I have mixed result (I was expecting less energy lost in those scenario).

Here is how it is setup, am I missing something ?

```xml
<scene version="3.0.0">
	<default name="width" value="1310"/>
	<default name="height" value="951"/>
	<integrator id="integrator" type="path"/>

	<bsdf type="roughplastic" id="dielectric-white">
		<rgb name="diffuse_reflectance" value="1.0, 1.0, 1.0"/>
		<float name="alpha" value="1.0"/>
	</bsdf>

	<emitter type="envmap" id="emitter-envmap">
		<string name="filename" value="Cubemaps/White.exr"/>
	</emitter>

	<shape type="obj">
		<string name="filename" value="Meshes/MatPreview.obj"/>
		<ref name="bsdf" id="dielectric-white"/>
		<transform name="to_world">
			<translate x="0" y="0" z="0"/>
		</transform>
	</shape>

	<sensor type="perspective">
		<float name="far_clip" value="1000.0"/>
		<float name="near_clip" value="0.01"/>
		<float name="fov" value="30.000000"/>
		<string name="fov_axis" value="x"/>
		<transform name="to_world">
			<rotate value="0.543846, -0.826436, 0.145723" angle="35.927731"/>
			<translate value="3.200000, 3.200000, -6.000000"/>
		</transform>
		<film type="hdrfilm">
			<integer name="height" value="$height"/>
			<integer name="width" value="$width"/>
		</film>
	</sensor>
</scene>
```

Here is the results with various roughness levels (0, 0.5 and 1.0)
![mitsubaG](https://github.com/mitsuba-renderer/mitsuba3/assets/62559283/b3036fdc-b0ff-4eb0-9e8a-f6e5fba149b3)
![mitsubaW](https://github.com/mitsuba-renderer/mitsuba3/assets/62559283/e1d71ac7-2d30-4efa-b0e1-f00871f392aa)

**Comment by merlinND** [comment] 2024-05-02 13:08
Hello @GMBethsoft,

I believe that some energy loss is to be expected from `roughplastic`, since it does not implement one of the more advanced energy-conserving microfacet models. However I don't know how much energy loss to expect at which roughness level.

As a sanity check, have you tried reproducing your experiment in PBRT and / or Blender? (Making sure to double check that the roughness parameter is defined in the same way, some systems take a `sqrt` mapping I believe).

**Comment by GMBethsoft** [comment] 2024-05-02 17:41
Thanks for the answer
I was also under the impression that there is no energy-conserving by looking at the code, but I wasn't sure.
Here some test I did in Blender (cycles).

This by using the Principled BSDF with base GGX distribution (metal = 0 and metal = 1)
![cyclesGGX_D_G](https://github.com/mitsuba-renderer/mitsuba3/assets/62559283/27757d43-2ff2-44b0-80a4-1d955550ba7e)
![cyclesGGX_M_G](https://github.com/mitsuba-renderer/mitsuba3/assets/62559283/7baace19-484b-4061-b730-ef87db928049)

And this is the result with the Multiscatter GGX
![cyclesMultiscatterGGX_D_G](https://github.com/mitsuba-renderer/mitsuba3/assets/62559283/84fc2fb3-ec33-4a2e-9bdd-ca050f60df22)
![cyclesMultiscatterGGX_M_G](https://github.com/mitsuba-renderer/mitsuba3/assets/62559283/f7375f7d-cb91-4ca0-88fa-50a6362ed934)

So their multiscatter GGX is correctly compensating the energy lost for roughness increase for metals. As for dielectrics, there is a slight energy increase in low roughness in both cases. Which is different from what I see for rough plastic.

**Comment by GMBethsoft** [comment] 2024-05-03 00:22
Thanks for the answer,
I was also under the impression that there is no energy-conservation by looking at the code, but I wasn't sure.

I did some test in Blender (cycles) with both GGX and Multiscatter GGX for dielectrics.
The multiscatter GGX is perfectly energy preservative, the GGX version is losing a bit of energy for high roughness but not that bad. So this is different from what I see for rough plastic.
![cyclesGGX_D_G](https://github.com/mitsuba-renderer/mitsuba3/assets/62559283/8117902f-d957-49b0-8178-486ac7be073e)
![cyclesMultiscatterGGX_D_G](https://github.com/mitsuba-renderer/mitsuba3/assets/62559283/28a2baf2-4c66-444e-bfb3-ad43dc110549)

I also did the metallic version, and for this one the Multiscattering version helps a lot
![cyclesGGX_M_G](https://github.com/mitsuba-renderer/mitsuba3/assets/62559283/d7183bbb-4472-41d5-8d72-ba78a72bd6cf)
![cyclesMultiscatterGGX_M_G](https://github.com/mitsuba-renderer/mitsuba3/assets/62559283/e84804ae-7059-4939-917e-b20aa7751884)

Not setup with PBRT yet to try this out, but this would interesting as well.

**Comment by njroussel** [comment] 2024-05-28 11:29
As mentioned above, some energy loss is expected.

I'll close this, I would need to see a comparison against Mitsuba 0.6 or PBRT before digging into this further. It is definitely possible that there is a bug in the current version.

**Closed by njroussel** 2024-05-28 11:29 UTC
